<a href="https://colab.research.google.com/github/coffta/first_python/blob/main/KIKAGAKU0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
np.__version__


'1.23.5'

In [ ]:
x = np.array([20, 40, 60])
x

array([20, 40, 60])

In [ ]:
t = np.array([60000, 115000, 155000])
t

array([ 60000, 115000, 155000])

In [ ]:
x_mean = x.mean()
x.mean()

40.0

In [ ]:
t_mean = t.mean()
t.mean()

110000.0

In [ ]:
#　x　の中心化
xc = x - x_mean
xc

array([-20.,   0.,  20.])

In [ ]:
#　t　の中心化
tc = t- t_mean
tc

array([-50000.,   5000.,  45000.])

最適なパラメータ

$$
w = \dfrac{\sum_{n-1}^{N} x_nt_n}{\sum_{n=1}^{N} x_nx_n^2}
$$

を求めます。

まずは分子

$$
{\sum_{n-1}^{N} x_nt_n}
$$

を求めます。

In [ ]:
#要素ごとの積
xc * tc

array([1000000.,       0.,  900000.])

In [ ]:
#要素ごとの積の総和
(xc * tc).sum()

1900000.0

分母

$$
{\sum_{n=1}^{N} x_nx_n^2}
$$

を求めます。

In [ ]:
xc * xc

array([400.,   0., 400.])

In [ ]:
(xc * xc).sum()

800.0

In [ ]:
#最適なパラメータ
w = (xc * tc).sum() / (xc * xc).sum()
w

2375.0

こちらのパラメータを用いて、$x = 50$の場合の予測値 $y$ を求めます。

$$
\begin{aligned}
y_{c} &= w x_{c} \\
y - \bar{t} &= w (x = \bar{x})\\
y &= \bar{t} + w (x = \bar{x})
\end{aligned}
$$

In [ ]:
x = 50
y = w * (x - x_mean) + t_mean
y

110500.0