<a href="https://colab.research.google.com/github/coffta/first_python/blob/main/KIKAGAKU0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
print('Hello world!!')


Hello world!!


In [ ]:
from google.colab import drive
drive.mount('/content/drive')


Mounted at /content/drive


In [ ]:
!ls 'drive/'


ls: cannot access 'drive/': No such file or directory


In [ ]:
!ls 'drive/'

ls: cannot access 'drive/': No such file or directory


In [1]:
import numpy as np


In [2]:
# ベクトルの定義
a = np.array([1, 2, 3])

a


array([1, 2, 3])

In [4]:
a.shape

(3,)

In [5]:
# 行列の定義
b = np.array(
    [[1, 2, 3],
     [4, 5, 6],
     [7, 8, 9]]
)

b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [6]:
print('Shape:', b.shape)
print('Rank:', b.ndim)

Shape: (3, 3)
Rank: 2


In [7]:
b.size

9

In [8]:
# 形を指定して、要素が全て 0 で埋められた ndarray を作る
a = np.zeros((3, 3))

a

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [9]:
# 形を指定して、要素が全て 1 で埋められた ndarray を作る
b = np.ones((2, 3))

b


array([[1., 1., 1.],
       [1., 1., 1.]])

In [10]:
# 形と値を指定して、要素が指定した値で埋められた ndarray を作る
c = np.full((3, 2), 9)

c

array([[9, 9],
       [9, 9],
       [9, 9]])

In [11]:
# 指定された大きさの単位行列を表す ndarray を作る
d = np.eye(5)

d


array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [12]:
# 形を指定して、 0 ~ 1 の間の乱数で要素を埋めた ndarray を作る
e = np.random.random((4, 5))

e

array([[0.34909755, 0.54698683, 0.07056455, 0.46870996, 0.95809655],
       [0.62621314, 0.4799803 , 0.73216149, 0.77630424, 0.23161465],
       [0.73510123, 0.17557077, 0.96147499, 0.45184488, 0.74589559],
       [0.95114894, 0.77576473, 0.35087187, 0.9367233 , 0.91654257]])

In [13]:
# 3 から始まり 10 になるまで 1 ずつ増加する数列を作る（10 は含まない）
f = np.arange(3, 10, 1)

f

array([3, 4, 5, 6, 7, 8, 9])